/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;

//import AppPackage.AnimationClass;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class Panel5 extends javax.swing.JPanel {

    /**
     * Creates new form Panel5
     */
    public Panel5() {
        initComponents();
        try{    
                Process r = Runtime.getRuntime().exec("chmod 777 /root/NetBeansProjects/Hadoop_installation2/src/MyFrames/MyPanels/root_login.sh");
                ProcessBuilder pb = new ProcessBuilder("/root/NetBeansProjects/Hadoop_installation2/src/MyFrames/MyPanels/root_login.sh");
                Process p = pb.start();
                BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()));
                String line = null;
                
                 while ((line = reader.readLine()) != null)
                    System.out.print(line);
                 System.out.println(" login successfully");
                }
            catch (IOException e){
                e.printStackTrace();
                 JOptionPane.showMessageDialog(null,"Please Login with ROOT then run that application");
            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtar1 = new javax.swing.JTextField();
        browse1 = new javax.swing.JButton();
        juntar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(152, 239, 227));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 3, 53)); // NOI18N
        jLabel1.setText("INSTALL JAVA 8");

        jtar1.setText("Browse java tar file ....");
        jtar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtar1ActionPerformed(evt);
            }
        });

        browse1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        browse1.setText("Browse");
        browse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse1ActionPerformed(evt);
            }
        });

        juntar.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        juntar.setText("Un-tar");
        juntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juntarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton1.setText("Install java");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("/root/Desktop/java1.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(juntar)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtar1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(browse1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browse1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(juntar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse1ActionPerformed
        // TODO add your handling code here:
        JFileChooser jc = new JFileChooser();
        jc.showOpenDialog(null);
        File f = jc.getSelectedFile();
        String filename = f.getAbsolutePath();
        jtar1.setText(filename);
       
    }//GEN-LAST:event_browse1ActionPerformed

    private void jtar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtar1ActionPerformed

    private void juntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juntarActionPerformed
        // TODO add your handling code here:
        
        Process p=null;
        ProgressBar pg=new ProgressBar();
        pg.setVisible(true);
        ProgressBar.Run r1=pg.new Run();
        new Thread(r1).start();
        String s=null;
        BufferedReader br2;
        String cmd="tar -xvzf "+jtar1.getText();
        try{p = Runtime.getRuntime().exec(cmd);
        br2 = new BufferedReader(
        new InputStreamReader(p.getInputStream()));
        //JOptionPane.showMessageDialog(null,"Please wait untill u get a message your file is Un-tarring...");
        while ((s= br2.readLine()) != null){
            System.out.println(s);
        }
            JOptionPane.showMessageDialog(null,"Un-tar finished....click to install java");
            pg.setVisible(false);
        }
        catch(IOException e){e.printStackTrace();}
      

    }//GEN-LAST:event_juntarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ProgressBar pg=new ProgressBar();
        pg.setVisible(true);
        ProgressBar.Run r1=pg.new Run();
        new Thread(r1).start();
        try {
            Runtime.getRuntime().exec("chmod 777 /root/NetBeansProjects/Hadoop_installation2/src/MyFrames/MyPanels/install_java1.sh");
            Process p=Runtime.getRuntime().exec("/root/NetBeansProjects/Hadoop_installation2/src/MyFrames/MyPanels/install_java1.sh 4");
            BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String line = null;
            while ((line = reader.readLine()) != null) 
                System.out.println(line);
     }
        catch (Exception e) {e.printStackTrace();}
        JOptionPane.showMessageDialog(null,"Java successfully updated");
        pg.setVisible(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        // TODO add your handling code here:
       /* AnimationClass ac=new AnimationClass();
        ac.jLabelYDown(0, 215, 10, 2, jLabel2);
        ac.jLabelYUp(215, 0, 10,2, jLabel2);*/
    }//GEN-LAST:event_jLabel2MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtar1;
    private javax.swing.JButton juntar;
    // End of variables declaration//GEN-END:variables
}
