/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;

import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author root
 */
public class Panel4 extends javax.swing.JPanel {
  
JList js1;
JScrollPane jsp1;
    /**
     * Creates new form Panel4
     */
    public Panel4() {
        initComponents();
        
         String faculty[]={"NAMENODE",
                           "CLUSTER",
                           "SECONDRY NAMENODE",
                           "DATANODE"
			};
	js1=new JList(faculty);
	jsp1=new JScrollPane(js1);
        js1.setToolTipText("select a NODE for their information");
        add(jsp1);
        jsp1.setBounds(10,30,170,100);
	js1.setBackground(Color.lightGray);
        js1.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                switch((String.valueOf(js1.getSelectedValue()))){
                    case "NAMENODE":
                        try {
                                Desktop d=Desktop.getDesktop();
                                d.browse(new URI("http://localhost:50070"));
                            } catch (Exception e1) {System.out.println(e1);}
                        break;
                    case "CLUSTER":
                        try {
                                Desktop d=Desktop.getDesktop();
                                d.browse(new URI("http://localhost:8088"));
                            } catch (Exception e1) {System.out.println(e1);}
                        break;    
                    case "SECONDRY NAMENODE":
                        try {
                                Desktop d=Desktop.getDesktop();
                                d.browse(new URI("http://localhost:50090"));
                            } catch (Exception e1) {System.out.println(e1);}
                        break;
                    case "DATANODE":
                        try {
                                Desktop d=Desktop.getDesktop();
                                d.browse(new URI("http://localhost:50075"));
                            } catch (Exception e1) {System.out.println(e1);}
                        break;    
                        
                }
            }
        });



    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(152, 239, 227));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
